//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int PublicationID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string PublicationTitle { get; set; }
        public string ArticleName { get; set; }
        public string PublisherName { get; set; }
        public string PublicationLocation { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
